name: Sync Upstream

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Sync Upstream
        continue-on-error: true
        run: |
          git config --global user.email "kevinnitro@duck.com"
          git config --global user.name "KevinNitroG"
          git remote add upstream https://github.com/j-hc/revanced-magisk-module.git
          git fetch upstream
          git merge upstream/main
          git tag -d main
          git push origin main

  ci:
    needs: sync
    uses: ./.github/workflows/ci.yml
