name: Sync Upstream

# env:
#   UPSTREAM_URL: "https://github.com/j-hc/revanced-magisk-module.git"
#   # WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
#   WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   UPSTREAM_BRANCH: "main"
#   DOWNSTREAM_BRANCH: "main"

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # - name: Sync Upstream
      #   uses: dabreadman/sync-upstream-repo@v1.3.0
      #   with:
      #     upstream_repo: ${{ env.UPSTREAM_URL }}
      #     upstream_branch: ${{ env.UPSTREAM_BRANCH }}
      #     downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
      #     token: ${{ env.WORKFLOW_TOKEN }}

      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Sync Upstream
        continue-on-error: true
        run: |
          git config --global user.email "kevinnitro@duck.com"
          git config --global user.name "KevinNitroG"
          git remote add upstream https://github.com/j-hc/revanced-magisk-module.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git tag -d main
          git push origin/main

  ci:
    needs: sync
    uses: ./.github/workflows/ci.yml
